remote_theme: glasnt/myrtle@thinkspace
repository: glasnt/remote-test

title_left    : "glasnt.com"
title_right   : # baseurl default   
url           : "https://glasnt.com"

description       : "in which glasnt tests the repo"    # EDIT       
baseurl           : "/remote-test"                      # EDIT
google_analytics  : G-265B4NHGG0                         
twitter_username  : "glasnt"     
postshare_enabled : true

permalink   : /:title/
markdown    : kramdown
highlighter : rouge

navbar:
  - slug : /
    title: home
  - slug : /blog/about/
    title: about
  - slug: /talks/
    title: talks
  - slug: /writing/
    title: writing
  - slug: /blog/
    title: blog
  - slug: /blog/now/
    title: now
  - slug: /blog/archive/
    title: archive
